### ISSUE TITLE
consider renaming to waku-react

### ISSUE THREAD

**Issue by vpavlin** [waku-org/waku-react#31]
Would it be possible to rename the repo to waku-react to make it more discoverable?

**Comment by hackyguru** [comment]
came here to say this but @vpavlin has alreadt spotted. few folks from thailand hacker house tried to search for react hooks but were unable to find it.. so it's definitely worth a rename

**Comment by hackyguru** [comment]
@weboko wdyt? can we rename the repository before ethistanbul for better visibility of react hooks?

**Comment by weboko** [comment]
This naming was done with other frameworks in mind: Vue, Angular. 
I think since React is prevailing - we can re-name it for now.
But ultimate goal I think would be to move to `js-waku` repo

**Comment by weboko** [comment]
Done
